import dotenv from "dotenv";
dotenv.config({ path: "../.env" });
import mongoose from "mongoose";
import Problem from "./models/Problem.js";

const problems = [
  {
    chapter: "Arrays & Hashing",
    chapterOrder: 1,
    topic: "Fundamentals",
    topicOrder: 1,
    title: "Two Sum",
    order: 1,
    youtubeUrl: "https://www.youtube.com/watch?v=KLlXCFGJgTk",
    leetcodeUrl: "https://leetcode.com/problems/two-sum/",
    codeforcesUrl: "",
    articleUrl: "https://leetcode.com/articles/two-sum/",
    level: "Easy",
  },
  {
    chapter: "Arrays & Hashing",
    chapterOrder: 1,
    topic: "Fundamentals",
    topicOrder: 1,
    title: "Contains Duplicate",
    order: 2,
    youtubeUrl: "https://www.youtube.com/watch?v=3OamzN90kPg",
    leetcodeUrl: "https://leetcode.com/problems/contains-duplicate/",
    codeforcesUrl: "",
    articleUrl: "https://www.geeksforgeeks.org/check-if-array-contains-duplicates/",
    level: "Easy",
  },
  {
    chapter: "Arrays & Hashing",
    chapterOrder: 1,
    topic: "Prefix & intervals",
    topicOrder: 2,
    title: "Product of Array Except Self",
    order: 1,
    youtubeUrl: "https://www.youtube.com/watch?v=bNvIQI2wA_k",
    leetcodeUrl: "https://leetcode.com/problems/product-of-array-except-self/",
    codeforcesUrl: "",
    articleUrl: "https://leetcode.com/articles/product-of-array-except-self/",
    level: "Medium",
  },
  {
    chapter: "Two Pointers",
    chapterOrder: 2,
    topic: "Basics",
    topicOrder: 1,
    title: "Valid Palindrome",
    order: 1,
    youtubeUrl: "https://www.youtube.com/watch?v=jJXJ16kPFWg",
    leetcodeUrl: "https://leetcode.com/problems/valid-palindrome/",
    codeforcesUrl: "",
    articleUrl: "https://www.geeksforgeeks.org/remove-characters-alphabet-string/",
    level: "Easy",
  },
  {
    chapter: "Two Pointers",
    chapterOrder: 2,
    topic: "Basics",
    topicOrder: 1,
    title: "3Sum",
    order: 2,
    youtubeUrl: "https://www.youtube.com/watch?v=onLoX6NwvVM",
    leetcodeUrl: "https://leetcode.com/problems/3sum/",
    codeforcesUrl: "",
    articleUrl: "https://leetcode.com/articles/3sum/",
    level: "Medium",
  },
  {
    chapter: "Linked List",
    chapterOrder: 3,
    topic: "Singly linked list",
    topicOrder: 1,
    title: "Reverse Linked List",
    order: 1,
    youtubeUrl: "https://www.youtube.com/watch?v=G0_I-ZF0S38",
    leetcodeUrl: "https://leetcode.com/problems/reverse-linked-list/",
    codeforcesUrl: "",
    articleUrl: "https://leetcode.com/articles/reverse-linked-list/",
    level: "Easy",
  },
  {
    chapter: "Linked List",
    chapterOrder: 3,
    topic: "Singly linked list",
    topicOrder: 1,
    title: "Merge Two Sorted Lists",
    order: 2,
    youtubeUrl: "https://www.youtube.com/watch?v=XIdigH959Ys",
    leetcodeUrl: "https://leetcode.com/problems/merge-two-sorted-lists/",
    codeforcesUrl: "",
    articleUrl: "https://www.geeksforgeeks.org/merge-two-sorted-linked-lists/",
    level: "Easy",
  },
  {
    chapter: "Trees",
    chapterOrder: 4,
    topic: "Binary tree traversals",
    topicOrder: 1,
    title: "Maximum Depth of Binary Tree",
    order: 1,
    youtubeUrl: "https://www.youtube.com/watch?v=hTM3phV6wgI",
    leetcodeUrl: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    codeforcesUrl: "",
    articleUrl: "https://leetcode.com/articles/maximum-depth-of-binary-tree/",
    level: "Easy",
  },
  {
    chapter: "Trees",
    chapterOrder: 4,
    topic: "Binary tree traversals",
    topicOrder: 1,
    title: "Binary Tree Level Order Traversal",
    order: 2,
    youtubeUrl: "https://www.youtube.com/watch?v=6ZnyEApgFYg",
    leetcodeUrl: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    codeforcesUrl: "",
    articleUrl: "https://leetcode.com/articles/binary-tree-level-order-traversal/",
    level: "Medium",
  },
  {
    chapter: "Graphs",
    chapterOrder: 5,
    topic: "BFS / DFS",
    topicOrder: 1,
    title: "Number of Islands",
    order: 1,
    youtubeUrl: "https://www.youtube.com/watch?v=pV2kpPD66nE",
    leetcodeUrl: "https://leetcode.com/problems/number-of-islands/",
    codeforcesUrl: "",
    articleUrl: "https://leetcode.com/articles/number-of-islands/",
    level: "Medium",
  },
  {
    chapter: "Graphs",
    chapterOrder: 5,
    topic: "BFS / DFS",
    topicOrder: 1,
    title: "Course Schedule",
    order: 2,
    youtubeUrl: "https://www.youtube.com/watch?v=EgI5nU9et3U",
    leetcodeUrl: "https://leetcode.com/problems/course-schedule/",
    codeforcesUrl: "",
    articleUrl: "https://leetcode.com/articles/course-schedule/",
    level: "Medium",
  },
  {
    chapter: "Dynamic Programming",
    chapterOrder: 6,
    topic: "1D DP",
    topicOrder: 1,
    title: "Climbing Stairs",
    order: 1,
    youtubeUrl: "https://www.youtube.com/watch?v=Y0lT9Fdg7zM",
    leetcodeUrl: "https://leetcode.com/problems/climbing-stairs/",
    codeforcesUrl: "",
    articleUrl: "https://leetcode.com/articles/climbing-stairs/",
    level: "Easy",
  },
  {
    chapter: "Dynamic Programming",
    chapterOrder: 6,
    topic: "1D DP",
    topicOrder: 1,
    title: "Longest Increasing Subsequence",
    order: 2,
    youtubeUrl: "https://www.youtube.com/watch?v=cjWnW0hdF1Y",
    leetcodeUrl: "https://leetcode.com/problems/longest-increasing-subsequence/",
    codeforcesUrl: "",
    articleUrl: "https://leetcode.com/articles/longest-increasing-subsequence/",
    level: "Medium",
  },
  {
    chapter: "Dynamic Programming",
    chapterOrder: 6,
    topic: "2D DP",
    topicOrder: 2,
    title: "Unique Paths",
    order: 1,
    youtubeUrl: "https://www.youtube.com/watch?v=IlEsdxuGD4k",
    leetcodeUrl: "https://leetcode.com/problems/unique-paths/",
    codeforcesUrl: "",
    articleUrl: "https://leetcode.com/articles/unique-paths/",
    level: "Medium",
  },
  {
    chapter: "Dynamic Programming",
    chapterOrder: 6,
    topic: "2D DP",
    topicOrder: 2,
    title: "Regular Expression Matching",
    order: 2,
    youtubeUrl: "https://www.youtube.com/watch?v=HAA66fpT5qw",
    leetcodeUrl: "https://leetcode.com/problems/regular-expression-matching/",
    codeforcesUrl: "",
    articleUrl: "https://leetcode.com/articles/regular-expression-matching/",
    level: "Tough",
  },
  {
    chapter: "Competitive extras",
    chapterOrder: 7,
    topic: "Codeforces practice",
    topicOrder: 1,
    title: "Watermelon (4A)",
    order: 1,
    youtubeUrl: "https://www.youtube.com/watch?v=9bCkA8TUvN8",
    leetcodeUrl: "",
    codeforcesUrl: "https://codeforces.com/problemset/problem/4/A",
    articleUrl: "https://codeforces.com/blog/entry/514",
    level: "Easy",
  },
  {
    chapter: "Competitive extras",
    chapterOrder: 7,
    topic: "Codeforces practice",
    topicOrder: 1,
    title: "Theatre Square (1A)",
    order: 2,
    youtubeUrl: "https://www.youtube.com/watch?v=9bCkA8TUvN8",
    leetcodeUrl: "",
    codeforcesUrl: "https://codeforces.com/problemset/problem/1/A",
    articleUrl: "https://www.geeksforgeeks.org/minimum-number-of-square-tiles-required-to-cover-a-given-rectangular-floor-area/",
    level: "Easy",
  },
];

async function run() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error("Set MONGODB_URI in .env");
    process.exit(1);
  }
  await mongoose.connect(uri);
  await Problem.deleteMany({});
  await Problem.insertMany(problems);
  console.log(`Seeded ${problems.length} problems`);
  await mongoose.disconnect();
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
